version: '3'

services:
  hello:
    image: hello
    deploy:
      replicas: 3
    ports:
      - 3005:3000
  goodbye:
    image: goodbye
    deploy:
      replicas: 5
    ports:
      - 3006:3000
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
